MODEL:
  VID:
    METHOD: "fgfa"
    ROI_BOX_HEAD:
      REDUCE_CHANNEL: True
  META_ARCHITECTURE: "GeneralizedRCNNFGFA"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  BACKBONE:
    CONV_BODY: "R-50-C4"
  ROI_BOX_HEAD:
    NUM_CLASSES: 12
    FEATURE_EXTRACTOR: "ResNetConv52MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
DATASETS:
  TRAIN: ("VID_VIS_train_15frames",)
  TEST: ("VID_val_videos",)